language: ruby
rvm:
- 2.3.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
deploy:
  provider: heroku
  app:
    master: redeemify-staging
  run: rake db:migrate
  api_key:
    secure: R8fEJTpEjoD9+3F+hMzuknKD3Uq/Nl7alfmnDepOQnHgZLIpsmC0aijBbCaYkAaknRzpvzWxl18FvNj9FBStWqCZhF7nIWBUfAQ3VTq3hEH1PP+Lyo5+QrJCg9o21wlkkGpmZ2Y8kXzafx/hGeMqHO9+eJ8tW7cKL5PFFT01bO17sqGobDqYl8Q2JmEwzFag+h5Oh3W77TQ65I037ldgpOhT7tXVy7G0ZoEuZHB7e7tvHnvpr2rLmHpTbuul0ZV1rN2xYKfD06BoG44Nj1JNhhhEd0GxTx7WlwSH9RcVZdxDaiaL/rwe9pQ15PhDfNvInP2+r1ukLOH+kVPLAfPTVhaWNlH9c7xz3chYA1g8fpG1YZs1IYt+fUh1NiMoR0i4U2FNtUz7mEbucDg8VPSvX4kNPa1RcNdMiEbGBW7pucMuG1pk0X+mf6Ju3ILPiZr6xAcP0SMODv2dDTAKP+aLHS1869WGjebX9BrvaqmoNmNTYNwARG6M1Z/HxKq6p6bUpvf8zCej+zRKGiZ+cZZX7xpSbCQKOtXaW1WAbXet6PcW+0nPWGzzpN446pZY+/grQ+tA7aSXVUwvYkzA8iEfgxcAIyZU4i3S7YTul8hvkLrzGMsTUDLKJL3FJA2ArBejhulxuDGfpURCCdOGpXXiQ0CaEzxndiH8zrvFlH8L+z8=
    
