development:
  adapter: postgresql
  database: redeemify_development
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: redeemify_staging
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: redeemify_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: redeemify_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test